In [6]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import sys

In [154]:
#SCC = pd.read_csv("../../data/Graph_1_5/SCC.csv")
#Louv = pd.read_csv("../../data/Graph_1_5/Louv.csv")
#LabelProp = pd.read_csv("../../data/Graph_1_5/LabelProp.csv")
#Leiden = pd.read_csv("../../data/Graph_1_5/Leiden.csv")
nodes = pd.read_csv("../../data/nodes.csv")
#Between = pd.read_csv("../../data/Graph_1_5/Betweeness.csv")
PageRank = pd.read_csv("../../data/Graph_1_5/PageRank.csv")
Closeness = pd.read_csv("../../data/Graph_1_5/closeness.csv")

In [164]:
nodes = pd.read_csv("../../data/nodes.csv")
#Between = pd.read_csv("../../data/Graph_1_5/Betweeness.csv")
PageRank = pd.read_csv("../../data/Test_Graph_1_5/PageRank.csv")
Closeness = pd.read_csv("../../data/Test_Graph_1_5/closeness.csv")

In [136]:
def community_det_acc(df1, df2):
    df1['Node_ID:ID'] = [int(i.strip('"')) for i in df1['Name'].tolist()]
    df1.drop(columns=['Name'], inplace=True)

    result_df = pd.merge(df1, df2, on='Node_ID:ID', how='inner')

    percentage_breakdown = result_df.groupby(['Community', 'Status:LABEL']).size().unstack(fill_value=0)
    
    percentage_breakdown_percentage = percentage_breakdown.div(percentage_breakdown.sum(axis=1), axis=0) * 100
    
    return percentage_breakdown_percentage

In [4]:
community_det_acc(SCC, nodes)

Status:LABEL  Hyperglycemia  Hypoglycemia     Normal
Community                                           
0                 33.248599     39.368729  27.382672

In [6]:
community_det_acc(Louv, nodes).head()

Status:LABEL  Hyperglycemia  Hypoglycemia     Normal
Community                                           
269               28.461538     38.076923  33.461538
289               18.891688     39.294710  41.813602
341               33.606557     32.377049  34.016393
355               36.790123     16.543210  46.666667
405               40.947368     39.473684  19.578947

In [5]:
community_det_acc(LabelProp, nodes).head()

Status:LABEL  Hyperglycemia  Hypoglycemia     Normal
Community                                           
1                 28.557030     19.603561  51.839409
6                 26.388069     31.069108  42.542823
28                34.192099     38.182058  27.625842
66                15.248227     35.106383  49.645390
78                 7.936508     50.793651  41.269841

In [6]:
community_det_acc(Leiden, nodes).head()

Status:LABEL  Hyperglycemia  Hypoglycemia     Normal
Community                                           
2                 39.507620     40.767878  19.724502
3                 27.090153     56.684066  16.225781
7                 31.702128     54.158607  14.139265
12                32.394366     17.706237  49.899396
14                99.894180      0.105820   0.000000

In [9]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from scipy.signal import find_peaks
from scipy.signal import peak_widths
from scipy.signal import peak_prominences
from scipy.integrate import simps
from sklearn.model_selection import StratifiedKFold

In [5]:
def clean_merge(Louv, nodes):
    Louv['Node_ID:ID'] = [int(i.strip('"')) for i in Louv['Name'].tolist()]
    Louv.drop(columns=['Name'], inplace=True)
    return pd.merge(Louv, nodes, on='Node_ID:ID', how='inner')

In [ ]:
Between['Node_ID:ID'] = [int(i.strip('"')) for i in Between['Name'].tolist()]
Between.drop(columns=['Name'], inplace=True)

In [32]:
result_df = pd.merge(Between, result_df, on='Node_ID:ID', how='inner')

NameError: name 'result_df' is not defined

In [165]:
#Leiden.rename(columns={'Community':'Leiden'}, inplace=True)
#LabelProp.rename(columns={'Community':'LabelProp'}, inplace=True)
#Louv.rename(columns={'Community':'Louv'}, inplace=True)
PageRank.rename(columns={'score':'PageRank'}, inplace=True)
#Between.rename(columns={'score':'Between'}, inplace=True)

In [166]:
Closeness.rename(columns={'score':'Closeness'}, inplace=True)

In [167]:
#result_df = clean_merge(Leiden, nodes)
#result_df = clean_merge(LabelProp, result_df)
#result_df = clean_merge(Louv, result_df)
#result_df = clean_merge(Between, result_df)
result_df = clean_merge(PageRank, nodes)
result_df = clean_merge(Closeness, result_df)

In [168]:
Closeness.rename(columns={'nodeId':'Name'}, inplace=True)

In [169]:
Closeness.rename(columns={'Name':'Node_ID:ID'}, inplace=True)

In [142]:
result_df = pd.merge(Closeness, result_df, on='Node_ID:ID', how='inner')

In [170]:
Closeness

Closeness  Node_ID:ID
0      0.466682     7322788
1      0.466299     1494157
2      0.465882     7575734
3      0.465847     3159493
4      0.465535     7304348
...         ...         ...
6250   0.232491     2438275
6251   0.230003     3687779
6252   0.227113     2437694
6253   0.227113     2437997
6254   0.226234     3687480

[6255 rows x 2 columns]

In [171]:
result_df

Closeness  Node_ID:ID  PageRank       SpecID  WaveNumber:float  \
0      0.466682     7322788  2.233763  210519-1-21          0.142222   
1      0.466299     1494157  2.226200  210217-2-18          0.138458   
2      0.465882     7575734  2.260380  210519-3-18          0.137432   
3      0.465847     3159493  2.227665  210315-1-00          0.143932   
4      0.465535     7304348  2.214612  210519-1-15          0.143932   
...         ...         ...       ...          ...               ...   
6250   0.232491     2438275  0.565687  210304-1-26          0.408075   
6251   0.230003     3687779  0.516316  210324-1-00          0.583942   
6252   0.227113     2437694  0.519647  210304-1-26          0.209284   
6253   0.227113     2437997  0.519647  210304-1-26          0.312956   
6254   0.226234     3687480  0.462893  210324-1-00          0.481638   

       Status:LABEL  Absorbance:float  GridSlot  
0     Hyperglycemia          1.000000   (5, 40)  
1     Hyperglycemia          1.000000   (5, 40)  
2     Hyperglycemia          1.000000   (5, 40)  
3      Hypoglycemia          1.000000   (5, 40)  
4     Hyperglycemia          1.000000   (5, 40)  
...             ...               ...       ...  
6250   Hypoglycemia          0.645893  (16, 25)  
6251         Normal          1.000000  (23, 40)  
6252   Hypoglycemia          0.223633    (8, 8)  
6253   Hypoglycemia          0.023021   (12, 0)  
6254         Normal          0.491744  (19, 19)  

[6255 rows x 8 columns]

In [172]:
result_df['GridSlot_x'] = 0
result_df['GridSlot_y'] = 0

for i, r in result_df.iterrows():
    result_df['GridSlot_x'][i], result_df['GridSlot_y'][i] = r['GridSlot'].split(',')
    result_df['GridSlot_x'][i] = int(result_df['GridSlot_x'][i].strip('('))
    result_df['GridSlot_y'][i] = int(result_df['GridSlot_y'][i].strip(')'))

/tmp/ipykernel_10801/1595376135.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['GridSlot_x'][i], result_df['GridSlot_y'][i] = r['GridSlot'].split(',')


In [173]:
result_df

Closeness  Node_ID:ID  PageRank       SpecID  WaveNumber:float  \
0      0.466682     7322788  2.233763  210519-1-21          0.142222   
1      0.466299     1494157  2.226200  210217-2-18          0.138458   
2      0.465882     7575734  2.260380  210519-3-18          0.137432   
3      0.465847     3159493  2.227665  210315-1-00          0.143932   
4      0.465535     7304348  2.214612  210519-1-15          0.143932   
...         ...         ...       ...          ...               ...   
6250   0.232491     2438275  0.565687  210304-1-26          0.408075   
6251   0.230003     3687779  0.516316  210324-1-00          0.583942   
6252   0.227113     2437694  0.519647  210304-1-26          0.209284   
6253   0.227113     2437997  0.519647  210304-1-26          0.312956   
6254   0.226234     3687480  0.462893  210324-1-00          0.481638   

       Status:LABEL  Absorbance:float  GridSlot GridSlot_x GridSlot_y  
0     Hyperglycemia          1.000000   (5, 40)          5         40  
1     Hyperglycemia          1.000000   (5, 40)          5         40  
2     Hyperglycemia          1.000000   (5, 40)          5         40  
3      Hypoglycemia          1.000000   (5, 40)          5         40  
4     Hyperglycemia          1.000000   (5, 40)          5         40  
...             ...               ...       ...        ...        ...  
6250   Hypoglycemia          0.645893  (16, 25)         16         25  
6251         Normal          1.000000  (23, 40)         23         40  
6252   Hypoglycemia          0.223633    (8, 8)          8          8  
6253   Hypoglycemia          0.023021   (12, 0)         12          0  
6254         Normal          0.491744  (19, 19)         19         19  

[6255 rows x 10 columns]

In [174]:
result_df.drop(columns={"GridSlot"}, inplace=True)

In [175]:
peaks_df = result_df

In [176]:
from sklearn.preprocessing import MinMaxScaler

# Assuming df is your DataFrame and 'column_name' is the column you want to normalize
column_name = 'PageRank'

scaler = MinMaxScaler()
peaks_df[[column_name]] = scaler.fit_transform(peaks_df[[column_name]])

In [ ]:
column_name = 'Widths:float'

scaler = MinMaxScaler()
peaks_df[[column_name]] = scaler.fit_transform(peaks_df[[column_name]])

In [177]:
peaks_df

Closeness  Node_ID:ID  PageRank       SpecID  WaveNumber:float  \
0      0.466682     7322788  0.914984  210519-1-21          0.142222   
1      0.466299     1494157  0.911425  210217-2-18          0.138458   
2      0.465882     7575734  0.927510  210519-3-18          0.137432   
3      0.465847     3159493  0.912114  210315-1-00          0.143932   
4      0.465535     7304348  0.905972  210519-1-15          0.143932   
...         ...         ...       ...          ...               ...   
6250   0.232491     2438275  0.130022  210304-1-26          0.408075   
6251   0.230003     3687779  0.106789  210324-1-00          0.583942   
6252   0.227113     2437694  0.108357  210304-1-26          0.209284   
6253   0.227113     2437997  0.108357  210304-1-26          0.312956   
6254   0.226234     3687480  0.081649  210324-1-00          0.481638   

       Status:LABEL  Absorbance:float GridSlot_x GridSlot_y  
0     Hyperglycemia          1.000000          5         40  
1     Hyperglycemia          1.000000          5         40  
2     Hyperglycemia          1.000000          5         40  
3      Hypoglycemia          1.000000          5         40  
4     Hyperglycemia          1.000000          5         40  
...             ...               ...        ...        ...  
6250   Hypoglycemia          0.645893         16         25  
6251         Normal          1.000000         23         40  
6252   Hypoglycemia          0.223633          8          8  
6253   Hypoglycemia          0.023021         12          0  
6254         Normal          0.491744         19         19  

[6255 rows x 9 columns]

In [178]:
grouped_df = peaks_df.groupby(["SpecID", "Status:LABEL"])[["Closeness", "PageRank"]].mean().reset_index()

In [179]:
# Splitting the dataframe into features (X) and target variable (y)
X = grouped_df.drop(['Status:LABEL', 'SpecID'], axis=1)
y = grouped_df['Status:LABEL']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=1234)

In [132]:
X.head(10)

Closeness  PageRank
0   0.288496  0.361732
1   0.308521  0.501889
2   0.291967  0.417291
3   0.292840  0.403652
4   0.300708  0.461456
5   0.349978  0.534784
6   0.303601  0.473981
7   0.310138  0.522738
8   0.300788  0.471446
9   0.275066  0.331725

In [127]:
rf = RandomForestClassifier(random_state=1234)
rf.fit(X_train, y_train)

# Initialising and fitting the Extra Trees classifier
et = ExtraTreesClassifier(random_state=1234)
et.fit(X_train, y_train)

ExtraTreesClassifier(random_state=1234)

In [128]:
def get_feature_importances(model, X):

    # Get feature importances
    feature_importances = model.feature_importances_

    # Creating a DataFrame to display feature importances
    feature_importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})

    # Sorting the DataFrame by importance in descending order
    feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

    # Show the top 10 most important features
    top_10_features = feature_importance_df.head(20)

    return top_10_features

In [129]:
def calculate_metrics(y_test, y_pred):

    # Calculate overall accuracy
    overall_accuracy = accuracy_score(y_test, y_pred)
    print(f"Overall Accuracy: {overall_accuracy}\n")

    # Calculate precision, recall, and F1-score for each class
    report = classification_report(y_test, y_pred)
    print("\nClassification Report:")
    print(report)

    # Show the confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred)
    print("\nConfusion Matrix:")
    print(conf_matrix)

In [180]:
# Making predictions on the test set
y_pred = rf.predict(X_test)

# Calculating and printing evaluation metrics
calculate_metrics(y_test, y_pred)

Overall Accuracy: 0.39526411657559196


Classification Report:
               precision    recall  f1-score   support

Hyperglycemia       0.35      0.86      0.50       184
 Hypoglycemia       0.60      0.14      0.22       182
       Normal       0.60      0.19      0.28       183

     accuracy                           0.40       549
    macro avg       0.51      0.39      0.33       549
 weighted avg       0.51      0.40      0.34       549


Confusion Matrix:
[[158  13  13]
 [147  25  10]
 [145   4  34]]


In [181]:
# Making predictions on the test set
y_pred = et.predict(X_test)

# Calculating and printing evaluation metrics
calculate_metrics(y_test, y_pred)

Overall Accuracy: 0.3879781420765027


Classification Report:
               precision    recall  f1-score   support

Hyperglycemia       0.36      0.82      0.50       184
 Hypoglycemia       0.40      0.14      0.20       182
       Normal       0.58      0.21      0.31       183

     accuracy                           0.39       549
    macro avg       0.45      0.39      0.34       549
 weighted avg       0.45      0.39      0.34       549


Confusion Matrix:
[[150  22  12]
 [141  25  16]
 [130  15  38]]


In [45]:
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=1234)

cv_results = cross_val_score(rf, X, y, cv=cv, scoring='accuracy')

In [164]:
print(cv_results)
print(f"Mean Accuracy: {cv_results.mean():.2f}")
print(f"Standard Deviation: {cv_results.std():.2f}")

[0.87248322 0.83557047 0.83892617 0.8557047  0.86241611 0.79530201
 0.83557047 0.80872483 0.82550336 0.83501684]
Mean Accuracy: 0.84
Standard Deviation: 0.02


In [93]:
get_feature_importances(rf, X)

Feature  Importance
10                                   PageRank_0.0-0.1    0.080990
0                                 Closeness_y_0.0-0.1    0.067745
11                                   PageRank_0.1-0.2    0.066122
2                 Closeness_y_0.2-0.30000000000000004    0.064850
13                   PageRank_0.30000000000000004-0.4    0.062745
3                 Closeness_y_0.30000000000000004-0.4    0.062525
4                                 Closeness_y_0.4-0.5    0.062055
12                   PageRank_0.2-0.30000000000000004    0.061707
1                                 Closeness_y_0.1-0.2    0.061029
6   Closeness_y_0.6000000000000001-0.7000000000000001    0.058530
14                                   PageRank_0.4-0.5    0.057814
5                                 Closeness_y_0.5-0.6    0.057154
16     PageRank_0.6000000000000001-0.7000000000000001    0.054902
15                                   PageRank_0.5-0.6    0.053486
7                  Closeness_y_0.7000000000000001-0.8    0.036016
17                    PageRank_0.7000000000000001-0.8    0.034945
18                                   PageRank_0.8-0.9    0.029279
8                                 Closeness_y_0.8-0.9    0.026694
19                                   PageRank_0.9-1.0    0.000716
9                                 Closeness_y_0.9-1.0    0.000697

In [94]:
get_feature_importances(et, X)

Feature  Importance
0                                 Closeness_y_0.0-0.1    0.076982
10                                   PageRank_0.0-0.1    0.072940
11                                   PageRank_0.1-0.2    0.068071
12                   PageRank_0.2-0.30000000000000004    0.063304
13                   PageRank_0.30000000000000004-0.4    0.060326
16     PageRank_0.6000000000000001-0.7000000000000001    0.059815
2                 Closeness_y_0.2-0.30000000000000004    0.058902
6   Closeness_y_0.6000000000000001-0.7000000000000001    0.057749
1                                 Closeness_y_0.1-0.2    0.057614
3                 Closeness_y_0.30000000000000004-0.4    0.057518
4                                 Closeness_y_0.4-0.5    0.057215
14                                   PageRank_0.4-0.5    0.055581
15                                   PageRank_0.5-0.6    0.055079
5                                 Closeness_y_0.5-0.6    0.054484
17                    PageRank_0.7000000000000001-0.8    0.039582
7                  Closeness_y_0.7000000000000001-0.8    0.039198
8                                 Closeness_y_0.8-0.9    0.031216
18                                   PageRank_0.8-0.9    0.029713
9                                 Closeness_y_0.9-1.0    0.002405
19                                   PageRank_0.9-1.0    0.002307

In [54]:
result_df

Closeness  Node_ID:ID  PageRank       Between   Louv  LabelProp  \
0       0.342238     5167722  0.628102  1.812212e+07   7870       4148   
1       0.340816     5168623  0.508633  1.639455e+07   7870       4148   
2       0.340037     5168215  0.796911  4.688332e+06  18505       4148   
3       0.339736     5197403  0.856466  6.900229e+06  46582          6   
4       0.339343     5196706  0.610537  2.251702e+07   7870        826   
...          ...         ...       ...           ...    ...        ...   
51922   0.129579     1197193  0.637295  0.000000e+00  14998      14839   
51923   0.129579     1197218  0.637295  0.000000e+00  14998      14839   
51924   0.129579     1197283  0.637295  0.000000e+00  14998      14839   
51925   0.129579     1197368  0.652680  0.000000e+00  14998      14839   
51926   0.129579     1197381  0.652680  0.000000e+00  14998      14839   

       Leiden       SpecID  WaveNumber:float  Absorbance:float   Status:LABEL  \
0           3  210407-1-02         532.80182         7956.8179   Hypoglycemia   
1           3  210407-1-02        1148.51940         9168.3438   Hypoglycemia   
2           7  210407-1-02         869.70386         4263.9268   Hypoglycemia   
3         410  210407-1-03        1008.42820         2218.3857   Hypoglycemia   
4           3  210407-1-03         532.11847         9018.3037   Hypoglycemia   
...       ...          ...               ...               ...            ...   
51922     270  210211-2-05         817.08429        34853.7660  Hyperglycemia   
51923     270  210211-2-05         834.16858        35904.6800  Hyperglycemia   
51924     270  210211-2-05         878.58771        28607.2050  Hyperglycemia   
51925     270  210211-2-05         936.67426        27065.9940  Hyperglycemia   
51926     270  210211-2-05         945.55811        27116.3030  Hyperglycemia   

       Widths:float  Prominences:float GridSlot_x GridSlot_y        Bin  
0          0.003874          5510.6140         10          7    500-600  
1          0.011829          7484.9468         22          9  1100-1200  
2          0.007954          2687.4705         17          4    800-900  
3          0.002878           177.0571         20          2  1000-1100  
4          0.002284          3260.3818         10          9    500-600  
...             ...                ...        ...        ...        ...  
51922      0.003476          2244.9710         16         34    800-900  
51923      0.050214         10884.4200         16         35    800-900  
51924      0.005185           882.1950         17         28    800-900  
51925      0.002308           395.6700         18         27   900-1000  
51926      0.021438          1215.3620         18         27   900-1000  

[51927 rows x 16 columns]

In [83]:
small_pg = result_df.nsmallest(int(0.75 * len(result_df)), 'PageRank')

In [84]:
small_pg

Closeness  Node_ID:ID  PageRank        Between   Louv  LabelProp  \
43720   0.255907     7517501  0.000000       0.000000  40051          1   
39869   0.270733      484813  0.008966       0.000000  21424          1   
50433   0.208930      361035  0.020301    4442.528753   3526        311   
39189   0.273312     5607088  0.022686    6747.341325  17535         28   
42180   0.261305       57890  0.029254    4490.952140  46582          6   
...          ...         ...       ...            ...    ...        ...   
33278   0.286005      529758  0.719857  108122.066545    811      49502   
26837   0.293702     3869781  0.719861   29878.471769  40051          6   
28258   0.292389     1627595  0.719861   30398.775594  29762          6   
31828   0.288100     2593183  0.719863  115471.347888  42349       4148   
46946   0.244300     7671657  0.719867   10402.802884   3526        311   

       Leiden       SpecID  WaveNumber:float  Absorbance:float   Status:LABEL  \
43720      87  210519-2-42        1895.44420         768.20282  Hyperglycemia   
39869      30  210114-2-34        1982.23230         951.05017         Normal   
50433     126  210114-1-38         227.33485         896.20660         Normal   
39189     398  210414-3-34        1869.47610        1834.22610         Normal   
42180     333  201210-1-22        1946.01370        1826.18520         Normal   
...       ...          ...               ...               ...            ...   
33278     104  210120-1-02         284.05466        2015.72110  Hyperglycemia   
26837     121  210324-2-19        1294.07740        1215.14640         Normal   
28258      84  210218-1-18        1430.06840        1428.27510  Hyperglycemia   
31828     136  210304-2-35         434.39636        6647.06250   Hypoglycemia   
46946     126  210519-3-06        1000.91110         580.79547  Hyperglycemia   

       Widths:float  Prominences:float GridSlot_x GridSlot_y        Bin  
43720      0.013047           83.99957         37          0  1800-1900  
39869      0.000567           76.09692         39          0  1900-2000  
50433      0.010738          113.27526          4          0    200-300  
39189      0.000452           77.25060         37          1  1800-1900  
42180      0.000735           81.48000         38          1  1900-2000  
...             ...                ...        ...        ...        ...  
33278      0.008252          106.93550          5          2    200-300  
26837      0.029356          156.72980         25          1  1200-1300  
28258      0.032951          186.81450         28          1  1400-1500  
31828      0.003468          186.36670          8          6    400-500  
46946      0.006623           86.46341         20          0  1000-1100  

[38945 rows x 16 columns]

In [94]:
# Pivot table with 'Absorbance', 'PeakWidths', and 'PeakProminences' as values
peak_bins = small_pg.pivot_table(index='SpecID', columns='Bin', values=['Widths:float', 'Prominences:float', 'GridSlot_x', 'GridSlot_y'], aggfunc='mean')
peak_bins.columns = [f"{col[0]}_{col[1]}" for col in peak_bins.columns]  # Combine column names
peak_bins.reset_index(inplace=True)

# Merge with 'Status' information
statuses = small_pg[['SpecID', 'Status:LABEL']].drop_duplicates()
peak_bins = pd.merge(peak_bins, statuses, on='SpecID')

# Set 'SpecID' as the index
peak_bins.set_index('SpecID', inplace=True)

# Fill NaN values with False
peak_bins.fillna(False, inplace=True)

C:\Users\stang\AppData\Local\Temp\ipykernel_13812\2536314543.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  peak_bins.fillna(False, inplace=True)


In [95]:
# Splitting the dataframe into features (X) and target variable (y)
X = peak_bins.drop(['Status:LABEL'], axis=1)
y = peak_bins['Status:LABEL']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [96]:
rf = RandomForestClassifier(random_state=1234)
rf.fit(X_train, y_train)

# Initialising and fitting the Extra Trees classifier
et = ExtraTreesClassifier(random_state=1234)
et.fit(X_train, y_train)

ExtraTreesClassifier(random_state=1234)

In [97]:
# Making predictions on the test set
y_pred = rf.predict(X_test)

# Calculating and printing evaluation metrics
calculate_metrics(y_test, y_pred)

Overall Accuracy: 0.7885906040268457


Classification Report:
               precision    recall  f1-score   support

Hyperglycemia       0.78      0.77      0.78       195
 Hypoglycemia       0.80      0.80      0.80       196
       Normal       0.79      0.80      0.79       205

     accuracy                           0.79       596
    macro avg       0.79      0.79      0.79       596
 weighted avg       0.79      0.79      0.79       596


Confusion Matrix:
[[151  20  24]
 [ 20 156  20]
 [ 22  20 163]]
